#export PS1="\[$(tput setaf 1)\][\[$(tput setaf 2)\]\u\[$(tput setaf 6)\]@\[$(tput setaf 5)\]\h \[$(tput setaf 6)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 3)\]\\$ \[$(tput sgr0)\]"
test -s ~/.alias && . ~/.alias || true
eval "$(starship init bash)"
eval "$(zoxide init bash)"

alias nb="newsboat"
alias nv="nvim"
alias py="python3"
alias ls="ls --color=auto"
alias yz="yazi"
alias pwroff="systemctl poweroff"
alias sus="systemctl suspend"
alias hibernate="systemctl hibernate"
alias reboot="systemctl reboot"
alias zs="zypper se"
alias zi="sudo zypper in"
alias zrm="sudo zypper rm -u"
alias zif="zypper if"
alias zlu="zypper lu"
alias zlr="zypper lr"
alias zref="sudo zypper ref"
alias zdup="sudo zypper dup"
alias img="wezterm imgcat"
alias fzf="fzf | xargs -r nvim"
alias cd="z"

export SDKMAN_DIR="/home/steinway/.sdkman"
[[ -s "/home/steinway/.sdkman/bin/sdkman-init.sh" ]] && source "/home/steinway/.sdkman/bin/sdkman-init.sh"
